### ISSUE TITLE
Quaternions, strings and vehicles

### ISSUE THREAD

**Issue by BigETI** [FiveMP/FiveMP-API#1]
I know that the public API is still in development, and that many functions are going to be implemented soon.
Thus I have questions regarding the public API:

1. Why would you distinguish between API::Entity::SetRotation() and API::Entity::SetQuaternion()?

2. Why is CVector4 used for quaternions?

3. Are we going to see std::wstring for functions that require string arguments?

4. When an object's rotation can be fully set at creation, why vehicles should not have that feature aswell? (API::Vehicle::Create())

Problems to:

1. A Quaternion is not an attribute but a mathematical object made of 4 components, that represents the quotient of two vectors in 3D space,
and rotation is a proper attribute that can be represented by eulers method, thus euler's rotation (x, y, z) or by Hamilton's number aka. quaternion.

2. Quaternions always have a magnitude of 1 (not respected by CVector4::CVector4()), and addition may cause the magnitude to change (CVector4::operator+()),
thus initializing arbitrary numbers (for example 0, 0, 0, 0) and addition between quaternions is not allowed in the first place.
CVector4 doesn't support multiplication between quaternions aswell.

3. std::string doesn't provide support for Unicode, but atleast UTF-8

4. If a vehicle is on a steep road, a vehicle may glitch into the ground due to the lack of a proper rotation value at creation.

Possible solutions to:

1. If you want programmers stick to quaternion rotation and still maintaining the accessibility to euler's rotation, you may consider using a rotation class that handles trivial math operations between quaternions, and conversion to and from euler's rotation.
You should make API::Entity::SetRotation() and API::Entity::GetRotation() accessible to quaternions instead and deprecate API::Entity::SetQuaternion() and API::Entity::GetQuaternion().
API::Entity::SetQuaternion() and API::Entity::GetQuaternion() may confuse programmers to believe that these functions are not associated to rotation operations, and ditch the idea to use them, where a rotation class would be more intuitive, without the hassle to storing them and calculating between euler's rotation and quaternion rotation.
Quaternion multiplication is useful for adding rotation on top of another rotation.

2. A class that represents quaternion rotations (explained above) should be implemented to keep the mathematical problems away from programmers.
CVector4 is not a good canditate for quaternions (the default constructor and the + operator breaks it)

3. std::wstring is made of wchar_t elements, which are 16 bits in length each, thus supporting the use of Unicode in C++.

4. Just have a rotation (quaternion rotation) argument on API::Vehicle::Create() instead of heading (vertical axis rotation)

**Comment by FiveMP** [comment]
1. We've completely moved away from Quaternions and went back to Euler Rotation, this actually made a few things much easier to complete. Therefore Vector4 is no longer used for rotation as argument.
2. I'll be making changes to the Vector4 class, thanks.
3. We'll most likely use wstring for such.
4. _API::Vehicle::Create()_ now also supports a Vector3 argument for rotation.

Public API will be updated once we've tested the latest changes.
